[project]
name        = "Kekik"
version     = "1.9.9"
description = "İşlerimizi kolaylaştıracak fonksiyonların el altında durduğu kütüphane.."
keywords    = ["Kekik", "KekikAkademi", "keyiflerolsun"]
license     = { text = "GPLv3+" }
readme      = "README.md"

authors = [
    { name = "keyiflerolsun", email = "keyiflerolsun@gmail.com" }
]

classifiers = [
    "Development Status :: 5 - Production/Stable",
    "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
    "Programming Language :: Python :: 3"
]

requires-python = ">=3.14"
dependencies    = [
    "pytz",
    "requests",
    "aiohttp",
    "httpx",
    "parsel",
    "cssselect",
    "simplejson",
    "rich",
    "tabulate",
    "pycryptodome",
    "redis"
]

[project.scripts]
domain2ip = "Kekik.Domain2IP:domain_sorgu"

[project.urls]
Homepage   = "https://github.com/keyiflerolsun/Kekik"
Repository = "https://github.com/keyiflerolsun/Kekik.git"
Issues     = "https://github.com/keyiflerolsun/Kekik/issues"

[build-system]
requires      = ["hatchling"]
build-backend = "hatchling.build"
